### ISSUE TITLE
Citation meta tags

### ISSUE THREAD

**Issue by jmulliken** [lmullen/americas-public-bible#11]
Please add the tags in the attached txt file to the index head. (Or provide a location in the repo where this should go, and @jmulliken will do it). Also load the attached png favicon where appropriate in the project and adjust the "path/to/stanford_up_favicon.png" callout in meta tag file
[meta-tags.txt](https://github.com/lmullen/americas-public-bible/files/9073417/meta-tags.txt)
![stanford_up_favicon](https://user-images.githubusercontent.com/17858407/178028293-d87a42c1-e08a-4f42-b689-b204313c35ac.png)

**Comment by lmullen** [comment]
Sure. Will do. I'm familiar with these tags because we also use them for [CRDH](https://crdh.rrchnm.org).

@jmulliken One question: Can we please put the project description in the `<meta name="description" ...` tag instead of the citation? That field is picked up in lots of places, such as the description that shows below search results in Google. So I think something more catchy than the citation would help.

I would use the abstract I sent Friederike, and also put it in the Twitter and OG fields which are currently `[TBD]`.

**Comment by jmulliken** [comment]
That makes sense, yes. We'll want to use the cover copy though (or a truncated version). We'll have the final version of that after copyediting.

Also, that ISBN is actually an old project's that I forgot to replace. Here's the correct one: 9781503605244

**Comment by lmullen** [comment]
@jmulliken This issue has been updated as far as I can take it.

- Please let me know the `citation_OCLC` once you have it.
- The cover image will need to be updated once we have the final version.

**Comment by jmulliken** [comment]
OCLC: 1347278919
Cover thumb: [https://sup.org/books/cite/?id=28910](https://sup.org/books/cite/?id=28910)

**Comment by lmullen** [comment]
@jmulliken This should be finished now that I have the OCLC. I've pasted what the citation tags look like on the front page below so you can check that I did it right.

```
<meta name="citation_title" content="America’s Public Bible: A Commentary" />
<meta name="citation_isbn" content="978-1-5036-0524-4" />
<meta name="citation_author" content="Mullen, Lincoln A." />
<meta name="citation_publication_date" content="2023" />
<meta name="citation_language" content="en" />
<meta name="citation_publisher" content="Stanford University Press" />
<meta name="citation_DOI" content="https://doi.org/10.21627/2022apb" />
<meta name="citation_OCLC" content="1347278919" />
```
